// User info
export const USER_UPDATE_PROFILE = 'USER_UPDATE_PROFILE';
export const USER_DELETE_PROFILE = 'USER_DELETE_PROFILE';

export const LOADING_SET_MESSAGE = 'LOADING_SET_MESSAGE';
export const LOADING_HIDE = 'LOADING_HIDE';

// events
export const EVENTS_UPDATE = 'EVENTS_UPDATE';
export const EVENTS_CLEAR = 'EVENTS_CLEAR';

// drawer
export const DRAWER_SET_OPTIONS = 'DRAWER_SET_OPTIONS';
export const DRAWER_IS_OPEN = 'DRAWER_IS_OPEN';
