// User info
export const USER_UPDATE_PROFILE = 'USER_UPDATE_PROFILE';
export const USER_DELETE_PROFILE = 'USER_DELETE_PROFILE';

export const LOADING_SET_MESSAGE = 'LOADING_SET_MESSAGE';
export const LOADING_HIDE = 'LOADING_HIDE';
